language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y groff; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-linux-64.sh; fi
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: EBxXqVjU7AGBOHbf9MWmmlEX7wpJwi8faLbUjKB19M5MzGSKdvSHTnRTFWLt80+1S1qr/PlZUxeyl+xGGQ1PFHvlALGUGVveVJ/5MGHP+aRhPJgvQ0A15KWQrba4Yy5rbw+DlAOznUmmn+cmnjeEdT3J9eLF73GKYtEWB6qT2E8=
  file:
    - "build-osx/*.zip"
    - "build/*.zip"
  on:
    repo: ericwa/ericw-tools
    tags: true
